<?php

/**
 * @file
 * Contains mysearch.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mysearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mysearch module.
    case 'help.page.mysearch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My custom search using react') . '</p>';
      return $output;

    default:
  }
}
